#!/usr/bin/env bash
# Regenerate THIRD-PARTY-NOTICES.txt from the ACTUAL dependency graph.
#
# propfix redistributes third-party code two ways: Go modules compiled into
# the binary (backend/go.mod — chi, cors, x/crypto, modernc.org/sqlite, ...)
# and npm packages bundled into the embedded React app (once it lands — see
# the caveat below). The mermaid/marked bundles vendored into the marketing
# site (site/assets/vendor/) are folded in too. MIT, BSD and ISC all require
# the copyright notice and licence text to travel with the copy.
#
#     ./scripts/gen-notices.sh
#
# The generated file is committed and copied to site/licenses.txt for the
# static marketing site. It is NOT hand-maintained.
#
# CAVEAT: as of this writing propfix's package.json declares only the
# frontend's own dependencies (react, vite, tailwind, ...) — there is no
# built app yet to bundle them into (src/ is mid-build; see the repo
# furniture report). The npm section below already walks the real
# package.json dependency graph, so it stays correct as that graph grows;
# nothing here is hand-listed.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

OUT="THIRD-PARTY-NOTICES.txt"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# --- Go modules: Elastic's go-licence-detector walks the real module graph
# (backend/go.mod) and reproduces each module's licence text from the module
# cache.
DETECTOR="$(command -v go-licence-detector || true)"
if [[ -z "$DETECTOR" ]]; then
  echo "==> installing go.elastic.co/go-licence-detector@v0.10.0"
  GOBIN="$TMP/bin" go install go.elastic.co/go-licence-detector@v0.10.0
  DETECTOR="$TMP/bin/go-licence-detector"
fi

echo "==> resolving Go module graph (backend/)"
(cd backend && go mod download)
(cd backend && go list -m -json all) | "$DETECTOR" \
  -includeIndirect \
  -noticeTemplate scripts/notices/go-modules.tmpl \
  -noticeOut "$TMP/go-notices.txt"

# --- npm packages actually declared for the app (production deps only).
echo "==> resolving npm dependency graph"
[[ -d node_modules ]] || npm ci
npx --yes license-checker-rseidelsohn \
  --production --json --excludePrivatePackages --start . \
  | node scripts/notices/npm-notices.mjs > "$TMP/npm-notices.txt"

echo "==> composing $OUT"
{
  cat <<'HEADER'
================================================================================
propfix — THIRD-PARTY NOTICES
================================================================================

This file is generated by scripts/gen-notices.sh from the actual dependency
graph. Do not edit it by hand.

propfix is distributed under the MIT licence (see LICENSE). It bundles the
third-party software listed below. Each entry gives the component name, its
version, the licence it is distributed under, and the full text of that
licence, as those licences require.

HEADER

  echo "================================================================================"
  echo "npm packages (the React app's declared dependencies)"
  echo "================================================================================"
  echo
  cat "$TMP/npm-notices.txt"

  echo "================================================================================"
  echo "Vendored browser assets (marketing site, site/assets/vendor/)"
  echo "================================================================================"
  echo
  for lic in site/assets/vendor/*.LICENSE; do
    [[ -e "$lic" ]] || continue
    echo "--------------------------------------------------------------------------------"
    cat "$lic"
    echo
  done

  echo "================================================================================"
  echo "Go standard library (compiled into the propfix binary)"
  echo "================================================================================"
  echo
  echo "--------------------------------------------------------------------------------"
  echo "Component : The Go Programming Language standard library"
  echo "Version   : $(go env GOVERSION)"
  echo "Licence   : BSD-3-Clause (plus the Go patent grant, reproduced below)"
  echo "--------------------------------------------------------------------------------"
  echo
  cat "$(go env GOROOT)/LICENSE"
  echo
  cat "$(go env GOROOT)/PATENTS"
  echo

  echo "================================================================================"
  echo "Go modules (compiled into the propfix binary, from backend/go.mod)"
  echo "================================================================================"
  echo
  if grep -q "^Module  :" "$TMP/go-notices.txt"; then
    cat "$TMP/go-notices.txt"
  else
    echo "None found by go-licence-detector."
    echo
  fi
} > "$OUT"

# site/ is the static marketing site, deployed separately from the binary —
# it gets its own copy of the notices.
cp "$OUT" site/licenses.txt

echo "==> wrote $OUT, site/licenses.txt ($(wc -l < "$OUT" | tr -d ' ') lines)"
